[toolchain]
channel = "1.75.0-x86_64-unknown-linux-gnu"

[features]
resolution = true
skip-lint = false

[programs.localnet]
token_claimer = "E2dMh4oEcsPJqfy13vdFqLy52W1tbws4n5jQ5j9XLP5G"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/keypair.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"

[rust]
version = "1.75.0"